import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Toaster } from 'sonner'
import { LanguageProvider } from '@/lib/LanguageContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <Toaster position="top-center" richColors />
         <LanguageProvider>
          <div className="w-full min-h-screen">
            <Header />
             <main id="home">
                {children}
              </main>
            <Footer />
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
